// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQM5ORmwZIgfLCm6QYPp1BLpU6kmIg90A',
    appId: '1:877360246883:web:your-web-app-id',
    messagingSenderId: '877360246883',
    projectId: 'beguile-ai',
    authDomain: 'beguile-ai.firebaseapp.com',
    storageBucket: 'beguile-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB323h5RJN7FvoLXu82m4qW13s7xrZjgHs',
    appId: '1:877360246883:android:f146b97aa08bc24dab4856',
    messagingSenderId: '877360246883',
    projectId: 'beguile-ai',
    storageBucket: 'beguile-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQM5ORmwZIgfLCm6QYPp1BLpU6kmIg90A',
    appId: '1:877360246883:ios:fb8f0e4928a953a7ab4856',
    messagingSenderId: '877360246883',
    projectId: 'beguile-ai',
    storageBucket: 'beguile-ai.firebasestorage.app',
    iosBundleId: 'Com.beguileai.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQM5ORmwZIgfLCm6QYPp1BLpU6kmIg90A',
    appId: '1:877360246883:ios:fb8f0e4928a953a7ab4856',
    messagingSenderId: '877360246883',
    projectId: 'beguile-ai',
    storageBucket: 'beguile-ai.firebasestorage.app',
    iosBundleId: 'Com.beguileai.app',
  );
}
